### ISSUE TITLE
Warehouse Receipt - Add option to print barcode

### ISSUE THREAD

**Issue by ljanua** [ljanua/sci_enco#17]
This item is duplicate
- Add menu option "Print Barcode" under operation menu
- Print Barcode with Title above

**Comment by abhishek090** [comment]
Waiting for a solution on warehouse reciept

**Comment by mihirchandradubey** [comment]
what should appear in the main UI Panel after clicking the menu item "Print Barcode" . If it to print barcode for products in the receipt that has been done in # 25
