### ISSUE TITLE
Warehouse Receipt - Add step on workflow to wait for "QC"

### ISSUE THREAD

**Issue by ljanua** [ljanua/sci_enco#20]
Reviewed and revised the process:
    - Change the action button to "Approve Quality"
    - The "Quality" step must be after the "Validate" step.  (validate means confirm order received correctly)
    - When the user opens the item he/she should see "Validate" button...instead "Quality" button
    - Once the user click "Validate"  then item moves to Status "Quality"
    - When the user click "Approve Quality" the item is moved to "Done"

**Comment by mihirchandradubey** [comment]
have sent the code ready for QA

**Comment by mihirchandradubey** [comment]
updated as requested by Roberto 
- Change the action button to "Approve Quality" - completed
- The "Quality" step must be after the "Validate" step. (validate means confirm order received correctly) - completed
- When the user opens the item he/she should see "Validate" button...instead "Quality" button -completed
- Once the user click "Validate" then item moves to Status "Quality" - Completed
- When the user click "Approve Quality" the item is moved to "Done"  - completed
