### ISSUE TITLE
Warehouse Menu - Add option "Reception" under "Operation" in top bar

### ISSUE THREAD

**Issue by ljanua** [ljanua/sci_enco#21]
A new option must be added in the Warehouse menu..
Under the option "Operation" and new option "Reception"
  - It will open a "List  View" show all Warehouse Receipt status "Ready" or "available"

**Comment by luizjan** [comment]
Clicking "Reception" will show the list of all "Warehouse Receipts" waiting to be received

**Comment by luizjan** [comment]
I think @ljanua must add more detail on the page. But it should be the same layout that exists today

**Comment by abhishek090** [comment]
@luizjan : Need navigation details on Community odoo installation to navigate to Warehouse

**Comment by ljanua** [comment]
Due delay in the project timeline, we will not implement Menu changes via Coding//
Going forward: all menu changes for this project will be done only in the front-end..
