### ISSUE TITLE
Product - Add warehouse and Print Barcode

### ISSUE THREAD

**Issue by ljanua** [ljanua/sci_enco#25]
- Add field for "Storage Location" when user enters product in warehouse receipt
       - Add option to print Barcode for all products in the order.

**Comment by abhishek090** [comment]
@ljanua Need Navigating in the screen to implement the change

**Comment by ljanua** [comment]
@You do not need to Install Stock Barcode module to print barcodes....It's only needed to scan the barcode

Navigation:
  1. In the "Warehouse/Inventory Module",,,
  2. View Dashboard
  3. Select "Receipts" inside the "Receipts" window...- Note that you must have at least 1 order waiting to be received
  4. Select the 1st order in the list
    
      Add new  option "Barcodes" under "Print" menu above the order detail
                     This open should print all barcodes for the order..In a single page.
                     Each product has 1 barcode. For Each barcode print it in a single/individual page. 
                      See barcode sample in PDF  attached.


To add "Storage Location" continue the navigation 
 - Click "Edit"
  -Select 1st product in the list
  - Select Tab "Inventory" inside the product detail

 New field Storage_Location (a text field ) must be added after field "Volume"
  
[Products Labels.pdf](https://github.com/ljanua/sci_enco/files/861299/Products.Labels.pdf)

Issue #26  has the new Barcode Layout

**Comment by mihirchandradubey** [comment]
attaching the zip files, as requested above the code has been done
