### ISSUE TITLE
Product - Barcode

### ISSUE THREAD

**Issue by ljanua** [ljanua/sci_enco#26]
Change the layout of Barcode:
   - Remove color background - keep it without
   - Remove Price
   - Align width of product name and Barcode

**Comment by abhishek090** [comment]
@ljanua Need more input on the requirement

**Comment by ljanua** [comment]
See new layout attached
[Products Labels.pdf](https://github.com/ljanua/sci_enco/files/861303/Products.Labels.pdf)

The XML is also attached: it's part of addons/product/reports/product_product_template.xml
[product_product_templates.txt](https://github.com/ljanua/sci_enco/files/861314/product_product_templates.txt)

**Comment by mihirchandradubey** [comment]
is it similar to # 25
