### ISSUE TITLE
Sales Quotation - Change color in email template

### ISSUE THREAD

**Issue by ljanua** [ljanua/sci_enco#27]
Change color of customer email template to match Encoparts

**Comment by abhishek090** [comment]
Looks like duplicate with issue #28

**Comment by ljanua** [comment]
Anvith.#27 and #28 are not duplicate...they must be done in sequence:
    #27 is only to change the template for Sales Quotation, which is the most important email
    #28 is to ensure that the same changes are applied to all other emails being sent to customers
