### ISSUE TITLE
Change all template of emails to customer to match Encopart colors

### ISSUE THREAD

**Issue by ljanua** [ljanua/sci_enco#28]
Same color change made in "Sales Quotation" must be done for all other emails being sent to customers

**Comment by ljanua** [comment]
Use background color #e1e6ed and font color: #2f2f30 on all forms and email templates that have any Shadow box. 
The emails sent to customer are:
    - Sales Quotation
    - Invoice confirmation

**Comment by abhishek090** [comment]
The header and footer color are changed for Sale quoatation. Need the location or navigation for Invoice Confirmation email send.
