### ISSUE TITLE
RFQ Email template for Supplier - Remove price amount

### ISSUE THREAD

**Issue by ljanua** [ljanua/sci_enco#29]
Remove amount from the email sent to Supplier

**Comment by abhishek090** [comment]
@ljanua Need Navigation to email sent to Supplier for the chenge need to be done

**Comment by ljanua** [comment]
To generate this email:
  - Open Purchase Module
  - Create new Purchase Order
  - Enter vendor and product
  - Once order is fill-out, save it and select "send email"

**Comment by abhishek090** [comment]
@ljanua To reflect the changes have to delete existing loaded template in database and upgrade "Purchases" module.
Navigation:
Settings->[Technical] Email ->Templates
Delete template by name "RFQ - Send by Email"
Override "mail_template_data.xml" under addons/purchase/data
Upgrade the application.
